feat(2.1.0): add cancellable tests
freeCodeCamp/freeCodeCampOS pull request #405
Opened 2023-11-27 09:48 UTC by ShaunSHamilton

Moves test logic into the `Worker` API to allow for cancellable tests.

2023-12-11 12:20 UTC, ojeytonwilliams requested changes
As far as I can see, this seems solid (just one bug with after each), but there are a few thing that could be a little tidier.

2023-12-11 12:56 UTC, ShaunSHamilton commented on .freeCodeCamp/tooling/tests/main.js
> +  // toggleLoaderAnimation(ws);
No, we never include this, because it is useful, but has not been added since about v1.0

2023-12-11 14:06 UTC, ShaunSHamilton commented on .freeCodeCamp/tooling/tests/main.js
> +        await eval(`(async () => {${beforeAll}})()`);
What if it is async and not a function?

2023-12-11 14:07 UTC, ShaunSHamilton commented on .freeCodeCamp/tooling/tests/test-worker.js
> +    error.text = e;
No, but the `text` is just a misnomer, because I did not want to do `error.error`

2023-12-11 14:09 UTC, ShaunSHamilton commented on .freeCodeCamp/tooling/tests/main.js
> +    const _afterEachOut = await eval(`(async () => { ${afterEach} })();`);
How do you see this working? `afterEach` is often something like:

```js
const afterEach = `
const a =1;
const b =2;
`;
```

2023-12-12 15:27 UTC, ojeytonwilliams commented on .freeCodeCamp/tooling/tests/main.js
> +        await eval(`(async () => {${beforeAll}})()`);
I don't follow. If it's not a function, it can't be used. If returns a Promise, it'll get awaited.

2023-12-12 15:36 UTC, ojeytonwilliams commented on .freeCodeCamp/tooling/tests/test-worker.js
> +    error.text = e;
Oh, can you send errors between threads? I know there are limits, but I hadn't tested sending an error.

2023-12-12 15:57 UTC, ojeytonwilliams commented on .freeCodeCamp/tooling/tests/main.js
> +        await eval(`(async () => {${beforeAll}})()`);
Feel free to resolve this, I just didn't want to hide it before you'd seen it.

2023-12-12 16:00 UTC, ojeytonwilliams commented on .freeCodeCamp/tooling/tests/main.js
> +    const _afterEachOut = await eval(`(async () => { ${afterEach} })();`);
That makes sense. Is the plan to have the last line of `afterEach` be a return statement?

2023-12-12 19:18 UTC, ShaunSHamilton commented on .freeCodeCamp/tooling/tests/main.js
> +    const _afterEachOut = await eval(`(async () => { ${afterEach} })();`);
Not purposefully.

2023-12-12 19:41 UTC, ojeytonwilliams commented on .freeCodeCamp/tooling/tests/main.js
> +    const _afterEachOut = await eval(`(async () => { ${afterEach} })();`);
I think it'll need to be. Otherwise, with the async function wrapper, `_afterEachOut` will be undefined.

2024-01-15 08:15 UTC, ShaunSHamilton commented on .freeCodeCamp/tooling/tests/main.js
> +        await handleCancelTests({
I prefer seeing/knowing `handleCancelTests` is an async function. Also, I wonder if there is ever an issue with how the callback/handler is cleaned up without awaiting?

2024-01-15 08:19 UTC, ShaunSHamilton commented on .freeCodeCamp/tooling/tests/test-worker.js
> +    error.text = e;
No, you cannot send `Error`s between threads, but an `AssertionError` nicely gets returned as a plain object literal

2024-01-15 08:23 UTC, ShaunSHamilton commented on .freeCodeCamp/tooling/tests/main.js
> +    const _afterEachOut = await eval(`(async () => { ${afterEach} })();`);
This is on purpose. `afterEach` is just to clean up tests that do things like creating files.

2024-01-15 08:46 UTC, ojeytonwilliams commented on .freeCodeCamp/tooling/tests/main.js
> +        await handleCancelTests({
As far as I know, there's no practical difference between a sync function that returns a Promise and an async function, so it shouldn't matter here.

2024-01-16 16:57 UTC, merged